server:
  port: 7000

spring:
  application:
    name: ms-userauth
  datasource:
    dirver-class-name: org.sqlite.JDBC
    url: 'jdbc:sqlite:${DB_LOCATION:DATA.db}'

jwt:
  secret: ${JWT_SECRET:test}


logging:
  path: ../log
  file:
    name: ${logging.path}/${spring.application.name}.log
    pattern:
      file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

mybatis:
  configuration:
    map-underscore-to-camel-case: true